Repository medik8s/node-healthcheck-operator, pull requests merged in 2024-04, with the labels that each got.

#307 skip remediation for excluded nodes
  controllers/nodehealthcheck_controller.go
  controllers/nodehealthcheck_controller_test.go
Labels: approved, lgtm

#308 Disable caching for namespaces
  main.go
Labels: approved, lgtm, ok-to-test

#306 Ensure MachineAPI is enabled before trying to use its resources
  controllers/cluster/capabilities.go
  controllers/cluster/upgrade_checker.go
  controllers/console/plugin.go
  controllers/initializer/init.go
  controllers/initializer/init_test.go
  controllers/initializer/suite_test.go
  controllers/machinehealthcheck_controller_test.go
  controllers/mhc/checker.go
  controllers/nodehealthcheck_controller.go
  controllers/resources/manager.go
  controllers/suite_test.go
  controllers/utils/utils.go
  main.go
Labels: approved, lgtm

#310 Prevent overriding of pullspec set by CI
  Makefile
  bundle.ci.Dockerfile
Labels: approved

#309 Revert "Ensure MachineAPI is enabled before trying to use its resources"
  controllers/cluster/capabilities.go
  controllers/cluster/upgrade_checker.go
  controllers/console/plugin.go
  controllers/initializer/init.go
  controllers/initializer/init_test.go
  controllers/initializer/suite_test.go
  controllers/machinehealthcheck_controller_test.go
  controllers/mhc/checker.go
  controllers/nodehealthcheck_controller.go
  controllers/resources/manager.go
  controllers/suite_test.go
  controllers/utils/utils.go
  main.go
Labels: approved, lgtm

#312 Minor refactoring to test code
  controllers/nodehealthcheck_controller_test.go
Labels: approved, lgtm

#313 missing skip remediation events
  controllers/nodehealthcheck_controller.go
  controllers/nodehealthcheck_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm

#317 leftovers from renaming container-build to container-build-ocp
  Makefile
Labels: approved, lgtm

#320 remove code usage of InFlightRemediation
  controllers/nodehealthcheck_controller.go
  controllers/nodehealthcheck_controller_test.go
  controllers/resources/status.go
  e2e/nhc_e2e_test.go
Labels: approved, lgtm

#318 Do not set timeout annotation on already succeeded remediation CR
  controllers/nodehealthcheck_controller.go
  controllers/nodehealthcheck_controller_test.go
Labels: approved, lgtm

#315 (v2) Ensure MachineAPI is enabled before trying to use its resources
  controllers/cluster/capabilities.go
  controllers/cluster/upgrade_checker.go
  controllers/console/plugin.go
  controllers/initializer/init.go
  controllers/initializer/init_test.go
  controllers/initializer/suite_test.go
  controllers/machinehealthcheck_controller_test.go
  controllers/mhc/checker.go
  controllers/nodehealthcheck_controller.go
  controllers/resources/manager.go
  controllers/suite_test.go
  controllers/utils/utils.go
  main.go
Labels: approved, lgtm

#321 prevent multiple "node unhealthy" events
  controllers/nodehealthcheck_controller.go
  controllers/nodehealthcheck_controller_test.go
Labels: approved, lgtm

#323 Fix Go version used in Dockerfile to build the binary
  Dockerfile
Labels: approved, lgtm
