Repository medik8s/node-healthcheck-operator, pull requests merged in 2024-01, with the labels that each got.

#278 Fix flaky tests
  .github/workflows/pre-submit.yaml
  controllers/initializer/init.go
  controllers/initializer/suite_test.go
  controllers/rbac/aggregation.go
  controllers/rbac/aggregation_test.go
Labels: approved, lgtm, do-not-merge/hold

#274 Fix handling unhealthy condition change
  controllers/nodehealthcheck_controller.go
  controllers/nodehealthcheck_controller_test.go
  docs/workflow.md
Labels: approved, lgtm

#277 Fix CR deletion for escalating remediation
  controllers/nodehealthcheck_controller_test.go
  controllers/utils/utils.go
Labels: approved, lgtm

#276 Fix etcd guard check for control plane remediation
  bundle/manifests/node-healthcheck-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/nodehealthcheck_controller.go
  controllers/nodehealthcheck_controller_test.go
  controllers/utils/etcd.go
  e2e/mhc_e2e_test.go
  e2e/nhc_console_e2e_test.go
  e2e/nhc_e2e_test.go
  e2e/utils/node.go
Labels: approved, lgtm

#279 Several CSV updates
  .github/workflows/post-submit.yaml
  .github/workflows/pre-submit.yaml
  .github/workflows/release.yaml
  Makefile
  bundle/manifests/node-healthcheck-operator.clusterserviceversion.yaml
  config/manifests/base/bases/node-healthcheck-operator.clusterserviceversion.yaml
  config/manifests/k8s/kustomization.yaml
  config/patches/common/kustomization.yaml
  config/patches/common/seccomp_patch.yaml
Labels: approved, lgtm

#280 Fix position of CSV's replaces field...
  .github/workflows/release.yaml
  Makefile
Labels: approved

#281 Fix ongoing remediation check in webhook
  api/v1alpha1/nodehealthcheck_webhook.go
  api/v1alpha1/nodehealthcheck_webhook_test.go
Labels: approved, lgtm

#282 Improve check for missing / misconfigured templates
  controllers/resources/templates.go
Labels: approved, lgtm

#284 Improve requeue
  controllers/nodehealthcheck_controller.go
Labels: approved, lgtm

#283 Improve control plane remediation
  controllers/nodehealthcheck_controller.go
  controllers/nodehealthcheck_controller_test.go
  controllers/utils/etcd.go
  go.mod
  go.sum
  vendor/github.com/medik8s/common/pkg/etcd/etcd.go
  vendor/github.com/medik8s/common/pkg/labels/labels.go
  vendor/modules.txt
Labels: approved, lgtm

#288 Watch templates for updating NHC status
  controllers/nodehealthcheck_controller.go
  controllers/nodehealthcheck_controller_test.go
  controllers/resources/manager.go
  controllers/resources/templates.go
  controllers/suite_test.go
  controllers/utils/mapper.go
Labels: approved, lgtm

#289 Event fixes and addition
  controllers/machinehealthcheck_controller.go
  controllers/nodehealthcheck_controller.go
  controllers/nodehealthcheck_controller_test.go
  controllers/resources/manager.go
  vendor/github.com/medik8s/common/pkg/events/events.go
  vendor/modules.txt
Labels: approved, lgtm

#287 Fix MHC node lease deletion
  controllers/machinehealthcheck_controller.go
  controllers/machinehealthcheck_controller_test.go
  e2e/e2e_suite_test.go
  e2e/mhc_e2e_test.go
  e2e/nhc_e2e_test.go
Labels: approved, lgtm

#291 Add FAR and MDR to CSV
  bundle/manifests/node-healthcheck-operator.clusterserviceversion.yaml
  config/manifests/base/bases/node-healthcheck-operator.clusterserviceversion.yaml
Labels: approved, do-not-merge/work-in-progress
